### ISSUE TITLE
Can't load theme

### ISSUE THREAD

**Issue by liuseemin** [btd1337/Cairo-Dock-macOS-Sierra-Style#1]
Thanks for the beautiful theme. here's some problems I ran into while using it:
Loads the theme and shows nothing.
Ran cairo-dock in terminal and got these error messages:

gldi_managers_get_config: assertion 'pKeyFile != NULL' failed
warning :  (/build/buildd/cairo-dock-3.4.1/src/gldit/cairo-dock-image-buffer.c:cairo_dock_load_image_buffer_from_surface:162)  
  An image has an invalid size, will not be loaded.
warning :  (/build/buildd/cairo-dock-3.4.1/src/gldit/cairo-dock-image-buffer.c:cairo_dock_load_image_buffer_from_surface:162)  
  An image has an invalid size, will not be loaded.
warning :  (/build/buildd/cairo-dock-3.4.1/src/gldit/cairo-dock-image-buffer.c:cairo_dock_load_image_buffer_from_surface:162)  
  An image has an invalid size, will not be loaded.

Environments:
- Cairo-dock version: 3.4.1
- Ubuntu gnome 16.04 LTS
- GNOME shell version: 3.18.3

**Comment by btd1337** [comment]
Ok, Thank you for letting me know. I'll analyze the problem.

**Comment by dwlsalmeida** [comment]
same here

**Comment by btd1337** [comment]
I have not been able to identify the problem with the theme. Apparently the error is with the Cairo Dock version. Try to update and see if the problem persists.

My version:

- Cairo-Dock version : 3.4.99.alpha1
- Compiled date      : Sep 21 2017 22:51:19
- Built with GTK     : 3.18
- Running with OpenGL: 0

![screenshot from 2018-03-02 00 55 08](https://user-images.githubusercontent.com/11943860/36882937-720ab430-1db5-11e8-8ec5-6d1b33f9e5bf.jpeg)

**Comment by dwlsalmeida** [comment]
Nope, same version as you. Still does not work.
